### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by joroMaser** [medigate-io/ida_medigate#3]
In `C:\Program Files\IDA Pro 7.6\plugins\ida_medigate`  I copied all files from the master 
then I write   `"C:/Program Files/IDA Pro 7.6/plugins/ida_medigate"`  in file
`%APPDATA%\Hex-Rays\IDA Pro\idapythonrc.py  `

Then I tried to run : `from ida_medigate.rtti_parser import GccRTTIParser`
But I got error :

```
Python>from ida_medigate.rtti_parser import GccRTTIParser
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files/IDA Pro 7.6/plugins\ida_medigate\rtti_parser.py", line 149, in <module>
    class GccRTTIParser(RTTIParser):
  File "C:\Program Files/IDA Pro 7.6/plugins\ida_medigate\rtti_parser.py", line 153, in GccRTTIParser
    OFFSET_FROM_TYPEINF_SYM = 2 * utils.WORD_LEN
TypeError: unsupported operand type(s) for *: 'int' and 'NoneTyp
```

**Comment by RoberaHaile** [comment]
Here are the steps I used to install it for IDA Pro 7.6 
1. cd into or create IDAUSR directory. This is 'C:\Users\<username>\AppData\Roaming\Hex-Rays\IDA PRO' in widows or $HOME/.idapro in Linux 
2. create a directory called 'plugins' inside IDAUSR directory and cd into it. 
3. git clone ida_medigate into the plugins directory. It will look like $IDAUSR/plugins/ida_medigate 
4. create idapythonrc.py in the base of IDAUSR directory (outside plugins directory) and add the following python code 
```python
import os, sys 
import idaapi 
sys.path.append(os.path.join(idaapi.get_ida_subdirs("plugins"), "ida_medigate"))
```
5. cd into the ida_medigate directory again and copy ida_refree plugin python file to the plugins directory
`cd $IDAUSR/plugins/ida_medigate && cp plugins/ida-refree/refree.py ..`
The final IDAUSR directory tree should look like this 

```
- idapythonrc.py 
- plugins/ 
    - ida_medigate/
        - ...
    - refree.py 
```
6. import ida_medigate as a module and use it. eg: 
```python 
import ida_medigate
```

**Comment by RoberaHaile** [comment]
WORD_LEN is not updated. My guess is the callback that sets WORD_LEN when a new database is opened is not firing. It is defined in `utils.py`

```python
#utils.py 

WORD_LEN = None
def update_word_len(code, old=0):
    global WORD_LEN
    info = idaapi.get_inf_structure()
    if info.is_64bit():
        logging.debug("is 32 bit")
        WORD_LEN = 8
    elif info.is_32bit():
        logging.debug("is 32 bit")
        WORD_LEN = 4

idaapi.notify_when(idaapi.NW_OPENIDB, update_word_len) 
```
One work-around is to import utils and call `update_word_len`, then try to import `GccRTTIParser`
```python
import ida_medigate 
ida_medigate.utils.update_len(1) 
form ida_medigate.rtti_parser import GccRTTIParser
```
